# syntax=docker/dockerfile:1

FROM omni-data as lfs
ENV DEBIAN_FRONTEND=noninteractive

USER root
RUN apt-get update && apt-get install -y \
  git-lfs \
  && rm -rf /var/lib/apt/lists/*
USER ${NB_USER}

FROM lfs

RUN mkdir $HOME/orig

# For development
RUN pip install -U pip
RUN pip install git+https://renkulab.io/gitlab/btraven/omni-cli/
RUN pip install poetry

COPY entrypoint.sh .

ENTRYPOINT [ "./entrypoint.sh" ]

