[tool.poetry]
name = "omni-cli"
version = "0.1.0"
description = ""
authors = ["btraven <btraven@sdf.org>"]
readme = "README.md"
packages = [{include = "omni_cli"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
renku = "^2.3.1"
# renku is pinning a specific version of requests
requests = "<2.28.2"
pyyaml = "^6.0"

[tool.poetry.scripts]
omni_cli = 'omni_cli.cli:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


